server {
  listen 12089;
  server_name www.thejobnotifier.in;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  location = /404.html {
    root /usr/share/nginx/html;
  }
}